### ISSUE TITLE
3.1 Secret

### ISSUE THREAD

**Issue by UnterluggauerSimon** [hisi14/LedController_Gruppe_F#16]
- > Die X-Hasura-Group-ID sollte nicht im Source-Code definiert werden (das Repository ist public, alle können das Secret lesen!)

- Neue Datei secret.txt (auf gleicher Ebene wie README.md ) anlegen, und die X-Hasura-Group-ID dort einfügen

- .gitignore (auf gleicher Ebene wie README.md ) anlegen, dort dann secret.txt eintragen, damit die Datei nicht commited wird

- Secret aus Code löschen und stattdessen aus Datei auslesen

- Real World: Wenn ein Secret einmal im Repo landet, muss es unbedingt ausgetauscht werden! Für Übung nicht nötig.

**Comment by florian-lirzer** [comment]
Issue closed with wrong task (#17) --> therefore manual close
